
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t ManiKumar/next-js-app
    - run: echo "${{secrets.DOCKERPWD}}" | docker login -u ${{secrets.DOCKERUSER}} --password-stdin 
    - run: docker push mani134/next-js-app:latest
